// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Whatsapp  string    `json:"whatsapp"`
	CreatedAt time.Time `json:"created_at"`
}

type Ticket struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Price       int64     `json:"price"`
	Stock       int32     `json:"stock"`
	CreatedAt   time.Time `json:"created_at"`
}

type Order struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	TicketID    *uuid.UUID `json:"ticket_id"`
	Quantity    int32     `json:"quantity"`
	TotalAmount int64     `json:"total_amount"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

type OrderItem struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	TicketID  uuid.UUID `json:"ticket_id"`
	Quantity  int32     `json:"quantity"`
	UnitPrice int64     `json:"unit_price"`
	Subtotal  int64     `json:"subtotal"`
	CreatedAt time.Time `json:"created_at"`
}

type Payment struct {
	ID            uuid.UUID  `json:"id"`
	OrderID       uuid.UUID  `json:"order_id"`
	DokuInvoiceNo string     `json:"doku_invoice_no"`
	PaymentUrl    string     `json:"payment_url"`
	Status        string     `json:"status"`
	PaidAt        *time.Time `json:"paid_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type Eticket struct {
	ID        uuid.UUID  `json:"id"`
	OrderID   uuid.UUID  `json:"order_id"`
	UserID    uuid.UUID  `json:"user_id"`
	TicketID  uuid.UUID  `json:"ticket_id"`
	QrCode    string     `json:"qr_code"`
	IsUsed    bool       `json:"is_used"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

// Joined result types (not direct table rows)

type OrderWithDetails struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	TicketID   uuid.UUID `json:"ticket_id"`
	UserName   string    `json:"user_name"`
	UserEmail  string    `json:"user_email"`
	TicketName string    `json:"ticket_name"`
}

type EticketDetails struct {
	UserName   string `json:"user_name"`
	TicketName string `json:"ticket_name"`
}

type OrderItemWithTicketName struct {
	TicketID   uuid.UUID `json:"ticket_id"`
	TicketName string    `json:"ticket_name"`
	Quantity   int32     `json:"quantity"`
}
