// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// ---- Tickets ----

const listTickets = `SELECT id, name, description, price, stock, created_at FROM tickets ORDER BY created_at ASC`

func (q *Queries) ListTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var t Ticket
		if err := rows.Scan(&t.ID, &t.Name, &t.Description, &t.Price, &t.Stock, &t.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

const getTicketByID = `SELECT id, name, description, price, stock, created_at FROM tickets WHERE id = $1 FOR UPDATE`

func (q *Queries) GetTicketByID(ctx context.Context, id string) (Ticket, error) {
	var t Ticket
	err := q.db.QueryRow(ctx, getTicketByID, id).Scan(&t.ID, &t.Name, &t.Description, &t.Price, &t.Stock, &t.CreatedAt)
	return t, err
}

type DecrementTicketStockParams struct {
	ID    string
	Stock int32
}

const decrementTicketStock = `UPDATE tickets SET stock = stock - $2 WHERE id = $1`

func (q *Queries) DecrementTicketStock(ctx context.Context, arg DecrementTicketStockParams) error {
	_, err := q.db.Exec(ctx, decrementTicketStock, arg.ID, arg.Stock)
	return err
}

// ---- Users ----

type UpsertUserParams struct {
	Name     string
	Email    string
	Whatsapp string
}

const upsertUser = `
INSERT INTO users (name, email, whatsapp)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name, whatsapp = EXCLUDED.whatsapp
RETURNING id, name, email, whatsapp, created_at`

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	var u User
	err := q.db.QueryRow(ctx, upsertUser, arg.Name, arg.Email, arg.Whatsapp).Scan(
		&u.ID, &u.Name, &u.Email, &u.Whatsapp, &u.CreatedAt,
	)
	return u, err
}

// ---- Orders ----

type CreateOrderParams struct {
	UserID      uuid.UUID
	TicketID    *uuid.UUID
	Quantity    int32
	TotalAmount int64
}

const createOrder = `
INSERT INTO orders (user_id, ticket_id, quantity, total_amount)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, ticket_id, quantity, total_amount, status, created_at`

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	var o Order
	err := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TicketID, arg.Quantity, arg.TotalAmount).Scan(
		&o.ID, &o.UserID, &o.TicketID, &o.Quantity, &o.TotalAmount, &o.Status, &o.CreatedAt,
	)
	return o, err
}

const getOrderByID = `SELECT id, user_id, ticket_id, quantity, total_amount, status, created_at FROM orders WHERE id = $1`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	var o Order
	err := q.db.QueryRow(ctx, getOrderByID, id).Scan(
		&o.ID, &o.UserID, &o.TicketID, &o.Quantity, &o.TotalAmount, &o.Status, &o.CreatedAt,
	)
	return o, err
}

type UpdateOrderStatusParams struct {
	ID     string
	Status string
}

const updateOrderStatus = `UPDATE orders SET status = $2 WHERE id = $1`

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}

const getOrderWithDetails = `
SELECT o.id, o.user_id, o.ticket_id, u.name, u.email, t.name
FROM orders o
JOIN users u ON u.id = o.user_id
JOIN tickets t ON t.id = o.ticket_id
WHERE o.id = $1`

func (q *Queries) GetOrderWithDetails(ctx context.Context, id string) (OrderWithDetails, error) {
	var d OrderWithDetails
	err := q.db.QueryRow(ctx, getOrderWithDetails, id).Scan(
		&d.ID, &d.UserID, &d.TicketID, &d.UserName, &d.UserEmail, &d.TicketName,
	)
	return d, err
}

// ---- Payments ----

type CreatePaymentParams struct {
	OrderID       uuid.UUID
	DokuInvoiceNo string
	PaymentUrl    string
}

const createPayment = `
INSERT INTO payments (order_id, doku_invoice_no, payment_url)
VALUES ($1, $2, $3)
RETURNING id, order_id, doku_invoice_no, payment_url, status, paid_at, created_at`

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	var p Payment
	err := q.db.QueryRow(ctx, createPayment, arg.OrderID, arg.DokuInvoiceNo, arg.PaymentUrl).Scan(
		&p.ID, &p.OrderID, &p.DokuInvoiceNo, &p.PaymentUrl, &p.Status, &p.PaidAt, &p.CreatedAt,
	)
	return p, err
}

const getPaymentByOrderID = `SELECT id, order_id, doku_invoice_no, payment_url, status, paid_at, created_at FROM payments WHERE order_id = $1`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	var p Payment
	err := q.db.QueryRow(ctx, getPaymentByOrderID, orderID).Scan(
		&p.ID, &p.OrderID, &p.DokuInvoiceNo, &p.PaymentUrl, &p.Status, &p.PaidAt, &p.CreatedAt,
	)
	return p, err
}

const getPaymentByInvoiceNo = `SELECT id, order_id, doku_invoice_no, payment_url, status, paid_at, created_at FROM payments WHERE doku_invoice_no = $1`

func (q *Queries) GetPaymentByInvoiceNo(ctx context.Context, invoiceNo string) (Payment, error) {
	var p Payment
	err := q.db.QueryRow(ctx, getPaymentByInvoiceNo, invoiceNo).Scan(
		&p.ID, &p.OrderID, &p.DokuInvoiceNo, &p.PaymentUrl, &p.Status, &p.PaidAt, &p.CreatedAt,
	)
	return p, err
}

const updatePaymentStatusPaid = `UPDATE payments SET status = 'paid', paid_at = NOW() WHERE id = $1`

func (q *Queries) UpdatePaymentStatusPaid(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePaymentStatusPaid, id)
	return err
}

const updatePaymentStatusFailed = `UPDATE payments SET status = 'failed' WHERE id = $1`

func (q *Queries) UpdatePaymentStatusFailed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updatePaymentStatusFailed, id)
	return err
}

// ---- Etickets ----

type CreateEticketParams struct {
	OrderID  uuid.UUID
	UserID   uuid.UUID
	TicketID uuid.UUID
	QrCode   string
}

const createEticket = `
INSERT INTO e_tickets (order_id, user_id, ticket_id, qr_code)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, user_id, ticket_id, qr_code, is_used, used_at, created_at`

func (q *Queries) CreateEticket(ctx context.Context, arg CreateEticketParams) (Eticket, error) {
	var e Eticket
	err := q.db.QueryRow(ctx, createEticket, arg.OrderID, arg.UserID, arg.TicketID, arg.QrCode).Scan(
		&e.ID, &e.OrderID, &e.UserID, &e.TicketID, &e.QrCode, &e.IsUsed, &e.UsedAt, &e.CreatedAt,
	)
	return e, err
}

const getEticketByQRCode = `SELECT id, order_id, user_id, ticket_id, qr_code, is_used, used_at, created_at FROM e_tickets WHERE qr_code = $1`

func (q *Queries) GetEticketByQRCode(ctx context.Context, qrCode string) (Eticket, error) {
	var e Eticket
	err := q.db.QueryRow(ctx, getEticketByQRCode, qrCode).Scan(
		&e.ID, &e.OrderID, &e.UserID, &e.TicketID, &e.QrCode, &e.IsUsed, &e.UsedAt, &e.CreatedAt,
	)
	return e, err
}

type MarkEticketUsedParams struct {
	QrCode string
	UsedAt time.Time
}

const markEticketUsed = `UPDATE e_tickets SET is_used = TRUE, used_at = $2 WHERE qr_code = $1`

func (q *Queries) MarkEticketUsed(ctx context.Context, arg MarkEticketUsedParams) error {
	_, err := q.db.Exec(ctx, markEticketUsed, arg.QrCode, arg.UsedAt)
	return err
}

const getEticketDetails = `
SELECT u.name, t.name
FROM e_tickets e
JOIN users u ON u.id = e.user_id
JOIN tickets t ON t.id = e.ticket_id
WHERE e.qr_code = $1`

func (q *Queries) GetEticketDetails(ctx context.Context, qrCode string) (EticketDetails, error) {
	var d EticketDetails
	err := q.db.QueryRow(ctx, getEticketDetails, qrCode).Scan(&d.UserName, &d.TicketName)
	return d, err
}

// ---- OrderItems ----

type CreateOrderItemParams struct {
	OrderID   uuid.UUID
	TicketID  uuid.UUID
	Quantity  int32
	UnitPrice int64
	Subtotal  int64
}

const createOrderItem = `
INSERT INTO order_items (order_id, ticket_id, quantity, unit_price, subtotal)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, ticket_id, quantity, unit_price, subtotal, created_at`

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	var oi OrderItem
	err := q.db.QueryRow(ctx, createOrderItem, arg.OrderID, arg.TicketID, arg.Quantity, arg.UnitPrice, arg.Subtotal).Scan(
		&oi.ID, &oi.OrderID, &oi.TicketID, &oi.Quantity, &oi.UnitPrice, &oi.Subtotal, &oi.CreatedAt,
	)
	return oi, err
}

const listOrderItems = `SELECT id, order_id, ticket_id, quantity, unit_price, subtotal, created_at FROM order_items WHERE order_id = $1 ORDER BY created_at ASC`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var oi OrderItem
		if err := rows.Scan(&oi.ID, &oi.OrderID, &oi.TicketID, &oi.Quantity, &oi.UnitPrice, &oi.Subtotal, &oi.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, oi)
	}
	return items, rows.Err()
}

const getOrderItemsWithTicketNames = `
SELECT oi.ticket_id, t.name, oi.quantity
FROM order_items oi
JOIN tickets t ON t.id = oi.ticket_id
WHERE oi.order_id = $1
ORDER BY oi.created_at ASC`

func (q *Queries) GetOrderItemsWithTicketNames(ctx context.Context, orderID uuid.UUID) ([]OrderItemWithTicketName, error) {
	rows, err := q.db.Query(ctx, getOrderItemsWithTicketNames, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItemWithTicketName
	for rows.Next() {
		var oi OrderItemWithTicketName
		if err := rows.Scan(&oi.TicketID, &oi.TicketName, &oi.Quantity); err != nil {
			return nil, err
		}
		items = append(items, oi)
	}
	return items, rows.Err()
}
